/*
 * Devguard Open Hardware API
 *
 * Although devguard does offer direct end to end encrypted connections, some users may prefer a third party to establish a connection for them, as it is done by data hungry cloud corporations.  The Open Hardware API can be called with any standard https client by passing an secretkit in the headers, and a devguard hosted webservice will establish a device connection on behalf of the user.  We still do not collect any data, however due to the nature of webservices, interception by third parties is possible and the OHA service comes with no waranty whatsoever. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"net/http"
	"github.com/gin-gonic/gin"
	"github.com/devguardio/oha/carrier"
	"github.com/devguardio/oha/db"
)

// HiClaimPost - Join a factory-reset device into your network
func HiClaimPost(c *gin.Context) {
    user := CurrentUserApi(c);
    if user == nil {return}

    secrets, err := db.LoadDefaultSecretKit(user);
    if err != nil {
        c.JSON(http.StatusBadRequest, err);
        return;
    }

    var target = c.Query("target");
    if target == "" {
        c.JSON(http.StatusBadRequest, &Error{
            Code:       "MissingTarget",
            Message:    "missing target= query parameter",
        });
        return;
    }

    err = carrier.HiClaim(c, secrets, target);
    if err != nil {
        c.JSON(http.StatusBadRequest, err);
        return;
    }

    _, err = db.CreateDevice (user, target);
    if err != nil {
        c.JSON(http.StatusBadRequest, err);
        return;
    }

    err = carrier.HiJoin(c, secrets, target);
    if err != nil {
        c.JSON(http.StatusBadRequest, err);
        return;
    }



	c.JSON(http.StatusOK, gin.H{})
}

// HiMeGet - Retreive User Data
func HiMeGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
